# Generated by Django 5.1.2 on 2024-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('ids', models.JSONField(blank=True, null=True)),
                ('camera_ids', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9, unique=True)),
                ('time_slots', models.ManyToManyField(related_name='day_schedules', to='schedule_app.timeslot')),
            ],
        ),
    ]
